### ISSUE TITLE
It is posible to contro by step/dir??? 

### ISSUE THREAD

**Issue by artayasa** [haotianh9/DengFOC_on_STM32#1]
Hi sir iam interesting with your project. 
It is posible to drive motor by step/dir??? 
And it posible to make big driver for ac servo 220v, amd with 2000ppr encorder sir?? 
I will wait for your reply. 
Thank uou so much.

**Comment by haotianh9** [comment]
Hello @artayasa,
     Thank you for your comments! This library is for brushless DC motors, and the main purpose is for starters, including myself, to learn the basics of motor control, instead of a library which works under broad scenario. 
     Stepper motor, driven by step/dir signals, uses a different control strategy. And high voltage is usually an issue of hardware in addition to software. I would suggest you to use some big libraries, like [Odrive](https://odriverobotics.com/).
     Thank you!
Yours sincerely,
Haotian

**Comment by xuezu29** [comment]
Hi, the period for the PWM is 2400, but in the foc calculation for duty, 1600 is used. Is this a mistake? thx!
